# version: '3.8' - the attribute `version` is obsolete, it will be ignored, removed it to avoid potential confusion

services:
  postgres:
    image: postgres:15-alpine
    container_name: rooster-postgres
    environment:
      POSTGRES_DB: rooster_ai_dev
      POSTGRES_USER: rooster_user
      POSTGRES_PASSWORD: rooster_password_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rooster_user -d rooster_ai_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: rooster-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
